name: Feature Request
description: Request a feature
labels: ["Feature Request"]
body:
  - type: textarea
    id: what-feature
    attributes:
      label: Description of the feature
      description: Describe what the feature is and how it works.
    validations:
      required: true
  - type: textarea
    id: why-add
    attributes:
      label: Why should this be added?
      description: Explain why this feature would be good for the mod.
    validations:
      required: true
